### PR TITLE
added support for PHP 7.3 up to PHP 8.0 and updated required dependencies

### PR DESCRIPTION
**Pull request by abame**
The following updates were implemented in this library
1. added support for PHP 7.3 up to PHP 8.0
2. updated flagception and doctrine DBAL to the latest version
3. updated dev dependencies to the latest version

### CODE REVIEW

**Comment by migo315** [comment]
Thanks for your contribution. Looks good to me.

I think we can remove Phing soon and call phpunit and co directly.

**Comment by migo315** [comment]
I tagged the changes as 1.1.0. ;-)

**Comment by abame** [comment]
> Thanks for your contribution. Looks good to me.
> 
> I think we can remove Phing soon and call phpunit and co directly.

That would be nice. I can do that in another PR in the upcoming days if that's ok with you

**Comment by abame** [comment]
> I tagged the changes as 1.1.0. ;-) 

Awesome ☺️

**Comment by migo315** [comment]
> That would be nice. I can do that in another PR in the upcoming days if that's ok with you

Of course. Any help is welcome. :-)

**Pull request merged**
